spring.datasource.url=jdbc:postgresql://localhost:5432/investfacil_db
spring.datasource.username=investfacil
spring.datasource.password=investfacil123

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true